### ISSUE TITLE
Cannot change from php74 to php73

### ISSUE THREAD

**Issue by ztobs** [sprintcube/docker-compose-lamp#118]
**Describe the bug**
After initial setup with php74, I then decided to change to php73 and add more extensions
But it still remained in php74 and extensions didnt add

**which Branch / PHP Version are you using ?**
php74

**To Reproduce**
1st run `docker-compose up -d` with the out of the box configuration
then update https://github.com/sprintcube/docker-compose-lamp/blob/master/bin/php73/Dockerfile#L43
to add extra extension as described 
`   docker-php-ext-install gettext && \
    docker-php-ext-install soap && \
    docker-php-ext-install bcmath && \
    docker-php-ext-install xsl && \
    docker-php-ext-install sockets
`
Also update the .env file 
https://github.com/sprintcube/docker-compose-lamp/blob/master/sample.env#L5
to
`PHPVERSION=php73`

Then run `docker-compose build` and  `docker-compose up -d`

**Expected behavior**
php version suppose to change to 7.3

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome
 - Docker Version: 
```
docker -v
docker version 19.03.8, build afacb8b7f0
```

**Comment by MrOffline77** [comment]
Hi, @ztobs 
you could try to build with `docker-compose build --no-cache ` but I would guess that you image names are somehow problematic. Did you change some image names ? Looks like docker uses an existing image to start your stack. I've tested this behavior going from php 5 => 7, nut not downwards. 
You can try to purge you php images, this should do the trick: 
`docker rmi docker-compose-lamp_webserver`
Otherwise check your docker images and purge all `docker-compose-lamp*`images. 
The `docker rmi docker-compose-lamp_webserver`should be link to 

Please let me know if this works for your.

**Comment by ztobs** [comment]
I rebuilt with no cache and it work. I was try to avoid redownloading the images due to limited internet.
