### ISSUE TITLE
Help with /var/www/html error

### ISSUE THREAD

**Issue by jleboube** [sprintcube/docker-compose-lamp#177]
I am trying to use this stack to deploy my own artifacts and run my site with this stack.  I continue to run into this issue where it complains about not being able to see /var/www/html.  I don't have a /var/www/html on my OS and I can't find where the container mounts it.  I'm not as worried about the db connectivity, as I can figure that out.  It is the /var/www/html that has me perplexed.  

![Screenshot from 2021-10-19 15-33-22](https://user-images.githubusercontent.com/6365166/137986829-3d388c8e-f7b4-4b78-a60a-32581e45100e.png)

I have tried adding `RUN usermod -u 1000 www-data` to my Dockerfile and doing a `docker-compose build` with no luck.  Any help/guidance would be greatly appreciated!

Ubuntu 20.04 is the OS I am using.

**Comment by jleboube** [comment]
Hi @armandojs ,

Thank you so much for taking the time to respond to my issue!!!  I will give this a shot.

**Comment by afarsh** [comment]
**For the database connectivity issue:**

Hey, I had a similar issue getting database connection fatal errors which took me a long time to realize and resolve (as a beginner). The fix was easy once you know it, of course. I am putting this here in case it helps anyone.

If you can't connect to mysql via localhost or 127.0.0.1 inside php container that is because there is no mysql installed in the php container. You must connect via the container name of your database. Or docker inspect your mysql container and get the container IP address.

**Comment by jleboube** [comment]
I agree. Once using the docker assigned IP address, connectivity was a breeze. Thanks for all of the help!

**Comment by MrOffline77** [comment]
Hi great to hear the community was able to help you. 
Please let us know if we can describe database related things better in the readme. I'm open to pull requests regarding this, since the database questions are popping up quite often.
