### ISSUE TITLE
You don't have permission to access this resource.

### ISSUE THREAD

**Issue by allcho** [sprintcube/docker-compose-lamp#210]
Hello
I did all with Readme.md and tried open website.local but getting error

**Forbidden**

**You don't have permission to access this resource.**
**Apache/2.4.38 (Debian) Server at website.local Port 80**

What the problem? How fix it? I using Ubuntu 22.04
My default.conf

```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot "./www/website.local"
    ServerName website.local
	<Directory "./www/website.local">
		AllowOverride all
	</Directory>
</VirtualHost>
```

My sample.env

```
PHPVERSION=php8
DOCUMENT_ROOT=./www
**APACHE_DOCUMENT_ROOT=./www**
VHOSTS_DIR=./config/vhosts
APACHE_LOG_DIR=./logs/apache2
PHP_INI=./config/php/php.ini
SSL_DIR=./config/ssl
```

/etc/hosts also I set

**Comment by klim2020** [comment]
I am not 100% sure but looks likr you have wrong .env and default.conf records
here s my .env
```
PHPVERSION=php74
DOCUMENT_ROOT=./www
APACHE_DOCUMENT_ROOT=/var/www/html
VHOSTS_DIR=./config/vhosts
APACHE_LOG_DIR=./logs/apache2
PHP_INI=./config/php/php.ini
SSL_DIR=./config/ssl
```

and vhosts
```
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot ${APACHE_DOCUMENT_ROOT}
    ServerName localhost
	<Directory ${APACHE_DOCUMENT_ROOT}>
		Options FollowSymLinks
                AllowOverride None
	</Directory>
</VirtualHost>
```
As you can see my APACHE_DOCUMENT_ROOT starts from / that means that inside a docker container it goes from root, 
so called absolute path.  but your path is relative(it starts from ./), wich means it starts from current folder. But it is very hard to tell what is the default folder for apache.
So on my opinion you should use an absolute path instead of relative.
