### ISSUE TITLE
[FEATURE] Use public intead of www??

### ISSUE THREAD

**Issue by arcanisgk** [sprintcube/docker-compose-lamp#217]
any way to use public directory instead of www for the document root directory?

**Comment by thephpx** [comment]
I assume you are talking about using /public directory inside the folder /www. In that case, I have normally updated the .env file and updated the value of APACHE_DOCUMENT_ROOT from /var/www/html to /var/www/html/public and restarted the docker instances. That always did the work for me.

Otherwise, if you want to use a folder named public instead of www. Updating the .env file should also work, just change everything that says ./www to ./public in the file and rebuild the docker images. Make sure you create the folder file.

**Comment by rbahala** [comment]
Thank you for email. Could you help me with my issue on the installation? I
did it with all default values (php8, mysql8, etc.) in my .env file. For
some reason, MySQL doesn't start with the error attached here.

[image: image.png]

**Comment by MrOffline77** [comment]
No update from issue creator - close.
