### ISSUE TITLE
How do I restart webserver?

### ISSUE THREAD

**Issue by namnguyen2091** [sprintcube/docker-compose-lamp#22]
Sorry, I dont know how to restart webserver.

**Comment by narendravaghela** [comment]
There are a few ways to do so.

### Restart the container
Simply, restart the containers via `docker-compose`.
```
docker-compose down
docker-compose up
```

### Restart the Apache from the container
You can log in to the web server container. Run following command from your terminal,
```
docker exec -it 7.2.x-webserver /bin/bash
```
Once you are in the container, run the restart command,
```
service apache2 restart
```

### Using the Kitematic (GUI for docker images)
Open the Kitematic and look for the webserver container from left panel. Select the container and restart it from the options.

**Comment by Cheslia** [comment]
I can get the container up and running, no issues.  I am also getting the permission issue so I tried to SSH using Putty to get to the container so that I could execute linux commands but even Putty's SSH is getting refused when I try to reach it at 127.0.0.1.  How do you get inside the container to execute commands?  On my work environment I bring up a totally separate docker linux box in the command window, but have to use docker toolbox on my home Windows as hyperV isn't allowed.  So struggling just trying to get a working web server up and running so I can start development against it.  Any help would be appreciated.

**Comment by namnguyen2091** [comment]
@narendravaghela I did it, thanks so much!
