### ISSUE TITLE
[SUGGESTION] Running docker-compose-lamp on resouce limited compute engines

### ISSUE THREAD

**Issue by c01dkit** [sprintcube/docker-compose-lamp#256]
Thx for convenient work!

I'm using Google's compute engine with 2 vCPUs and less than 1GB memory. When starting the `docker compose up -d`, it stucks the whole system right way. Even ssh connection was stopped. Then I set some disk space as swap file, everything was OK.

![image](https://github.com/sprintcube/docker-compose-lamp/assets/62790045/23523f23-24b5-44f6-8079-feb4dc0d9103)

A little comment is that, the minimum system requirements (e.g. system memory should be larger than 4GB ) could be mentioned in the README.

**Comment by MrOffline77** [comment]
Hi there, thanks for providing your Feedback. The stack is build with local development in mind. So the project somehow assumes that your are not running a coding stack on a 1GB RAM box :D. The problem is, I know that many people run this on other boxes. But the project scope would incredibly increase in terms of security considerations when we would acknowledge this. 
Its already starting with the fact, that you shouldn't run mod_php in production. Which would break the whole project structure somehow. I mean its possible, but as a maintainer I do not habe the capacity to do this alone in my free time, at least not at the moment. Maybe this will come at some point in the future.
