### ISSUE TITLE
DB connection of Docker LAMP

### ISSUE THREAD

**Issue by mix49** [sprintcube/docker-compose-lamp#46]
Hi there,
Many thanks for your great docker compose lamp. I installed it successfully on Ubuntu 19, then I wanted to try an open source software. After I created my database, I used localhost as a database host name like when I installed LAMP locally but I got an error connection message.
I used mysql instead localhost for database host name and my problem was solved. I found this database host name from test_db.php file in www directory.
Have a lot of fun

**Comment by MrOffline77** [comment]
Hi @mix49 thank you for the great feedback <3. 

The "mysql" instead of "localhost" is related to the docker-compose link. The web container see's the mysql not as localhost, because they dont share a real loopback device. Instead of this docker-compose links the two containers together to a fake loopback localhost. Therefore you need to pass mysql as database host for your application running inside the webserver container. 

When using other tools you like mysequel pro and so on, you can use localhost:3306 from your ubuntu to connect to the database with third party management tools.

**Comment by parkbroom** [comment]
@MrOffline77 what if the production server is using "localhost" as the connection.

do you have any suggestions?

**Comment by MrOffline77** [comment]
Hi @parkbroom 
usually you want to handle this with .env files inside you application. I guess you cant handle this for production in this case for any reason. But you want to use "localhost" on you local development machine because you directly pushing to production. 

If you really need localhost for whatever reason, you could adjust the docker-compose.yaml
In row 19 is the name of the mysql container defined. When you move this to localhost, the mysql should be response on localhost. But I'm not sure if docker-compose is checking that this is not THE real localhost. In addition you need to change the "link mysql" parts in the compose to localhost and also modify the php myadmin admin access at the bottom. 
Please note that the default index.php still wants to connects via mysql. So don't be afraid if that is not possible. You could change this too, if the solution wit name localhost works. 

If this doesn't work, you should change your mysql to localhost before pushing, or introduce an environment variable handler for your application. Even this Docker Project has one :), 

Please tell us if you were able to fix your problem.

**Comment by parkbroom** [comment]
Thanks for the fast reply @MrOffline77 .  

It is a "new" legacy project I am currently working in and connections are hardcoded via .php files.

Thanks for the two suggestions!

**Comment by MrOffline77** [comment]
you are welcome. I will close this one.
