### ISSUE TITLE
MySQL connecttion failed: Connection refused

### ISSUE THREAD

**Issue by manish-hk** [sprintcube/docker-compose-lamp#59]
mysqli_connect is not working on index.php

The index.php page is throwing error that MySQL connecttion failed: Connection refused

whereas test_db.php says Success: A proper connection to MySQL was made! The docker database is great. Host information: mysql via TCP/IP

**Comment by MrOffline77** [comment]
Hi, I can't reproduce this. Please try to create a fresh new clone and take a look if this still occures.

**Comment by Ashleybrandon** [comment]
I'm experiencing the same error with Phpmyadmin. Think there was an intermittent message saying 'connection timeout', but restarting Docker or the computer didn't help. Was just doing a simple PDO exercise.

**Comment by irisvn** [comment]
you try change 'localhost' to 'mysql'. Goodluck ^^

**Comment by manish-hk** [comment]
Default MySql is not root. Changed it to root and it worked.

**Comment by Gfast2** [comment]
> you try change 'localhost' to 'mysql' in config PHP file. Goodluck ^^

That light up my day! Thank you for your efforts!

**Comment by Gfast2** [comment]
The thing is, if it's hard to figure out, it may very hard to let seasonal php developer like me to jump back to php (right now js/ts developer). This is repo is popular & valuable, you may really wanna reduce over heads like this for all possible developers. Since PDO is kinda "way to go", please consider to add another db test php file in this repo for PDO. When PR wished, I may give it a try. If won't wait any further here it is:
```
<?php
$DBhost = "mysql";
$DBport = "3306";
$DBuser = "root";
$DBpass = "tiger";
try{
    $database = 'mysql:host=' . $DBhost . ':' . $DBport;
} catch(PDOException $e) {
    echo "php connect to mysql failed";
}

echo "looking awesome";

$file_db = new PDO($database, $DBuser, $DBpass);
?>
```

Have a nice & awesome day I wish you!

**Comment by MrOffline77** [comment]
@Gfast2 I see no disadvantage in adding a pdo database connection test. Feel free to create a PR for this against master branch.

**Comment by Gfast2** [comment]
https://github.com/sprintcube/docker-compose-lamp/pull/111

**Comment by jexjws** [comment]
""
the webserver service cannot use localhost as the address to connect to the database service. In Docker Compose, services can communicate with each other using their service names. Therefore, the webserver service should use database as the hostname to connect to the database service.

This is because Docker Compose creates a default network internally, and the container names of each service are automatically resolved to their internal IP addresses. So, in the webserver service, you should use database as the address in your connection string, and the Docker internal network will automatically handle the resolution of the name to the correct internal IP address.
""
