### ISSUE TITLE
phpmyadmin large files not uploading

### ISSUE THREAD

**Issue by manish-fn** [sprintcube/docker-compose-lamp#94]
it is a 8 mb file

php.ini settings
memory_limit = 900M
post_max_size = 800M
upload_max_filesize = 600M
file_uploads = On

No data was received to import. Either no file name was submitted, or the file size exceeded the maximum size permitted by your PHP configuration. See FAQ 1.16.

**Comment by MrOffline77** [comment]
This is probably because the phpmyadmin comes with its own php, and does not use the php.ini settings from the webserver due to its a completely different instance in a different docker container. 

You can change this behavior when you add a variable called `UPLOAD_LIMIT` and set a higher value inside the docker-compose file inside the php-myadmin part. 

You can also check the docs to this here: https://hub.docker.com/r/phpmyadmin/phpmyadmin/

please let me know if this solved your problem.

**Comment by manish-fn** [comment]
It worked well with the phpmyadmin environment variable UPLOAD_LIMIT.

Thanks @MrOffline77
